GET http://localhost:53795/flask/iris
Accept: application/json

### 
GET http://localhost:53795/flask/interop
Accept: application/json

###
GET http://localhost:53795/flask/posts
Accept: application/json

###
GET http://localhost:53795/flask/posts/1
Accept: application/json

###
POST http://localhost:53795/flask/posts
Content-Type: application/json
Accept: application/json

{
  "title": "foo",
  "content": "bar"
}